### ISSUE TITLE
Roadmap (RFC2 implementation, "phase II")

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain#1]
**First workable pre-α** (late spring)
- [x] Transactor ([milestone](https://github.com/mediachain/mediachain/milestones/Transactor%20Design)) _vyzo + bigs_
- [x] ~~L-SPACE read peer ([milestone](https://github.com/mediachain/mediachain/milestones/Read%20Client)) _yusef + arkadiy_~~
- [x] CLI (read) ([issue](https://github.com/mediachain/mediachain-cli/issues/1)) _bigs_
- [x] Dummy writer client: writes pre-crafted entries
- [x] CLI (write) (needs planning) _?_
  - either gRPC CLI or invoking client code directly

_What we have at this point_:
- local testnet
- transactors = n, read client = 1, write client = dummy, block size = m
- write some data (pre-crafted), read some data (no merging)
- datastore backed by Dynamo
- interfaces semi-stable

**α.1** (summer)
- indexer ([milestone](https://github.com/mediachain/mediachain/milestones/Indexer)) _tim_
- data store: switch to IPFS _?_
- translator/writer client: actually translates external writes _yusef + arkadiy_
  - port over translation code (maybe also separate translator?)
  - ~~client <> transactor service API defs ([issue](https://github.com/mediachain/mediachain/issues/25))~~ (this is just copycat PUT rn)
  - ignore deduplication etc for now
- Orchestration (needs planning) _?_
  - docker-compose ensemble?

_What we have at this point_:
- testnet deployed on EC2
- transactors = n, syndicated read clients = 2+, writer client = 1, indexer client = 1, block size = m
- write real data, possibly merge some data, possibly basic deduplication at write
- datastore backed by IPFS
- interfaces stable

**α.2** (late summer)

**Comment by bigs** [comment]
@parkan atm peer discovery is not really necessary as we have a single, complete quorum

**Comment by parkan** [comment]
Ok, @bigs @vyzo can we separate transactor-related steps into "absolute bare minimum that a transaction can be recorded", "healthy network" and "healthy/scalable network" type buckets? I imagine there's some work that's still on top of copycat but not strictly necessary for a single node to accept and record a transaction.

**Comment by parkan** [comment]
Closing this in favor of the milestone-based roadmap
