### ISSUE TITLE
Open testnet to the public (!)

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain#131]
- [x] Stabilize the grpc frontend #129
- [ ] ingest our seed datasets #149
- [x] Run thorough end to end performance testing #132 #144
- [x] Public datastore interface (set up a few rpc servers in ec2 with the grpc port open to the public) #150
  - [x] client side: https://github.com/mediachain/mediachain-client/issues/29
- [ ] client for people to use the testnet, which also provides access to the datastore  
  - [x] https://github.com/mediachain/mediachain-client/issues/16
  - [ ] https://github.com/mediachain/mediachain-client/issues/22
- [ ] Documentation 
  - [ ] https://github.com/mediachain/mediachain/issues/148
  - [ ] https://github.com/mediachain/mediachain-client/issues/30

**Comment by denisnazarov** [comment]
@vyzo @parkan can you throw up a check-list about what needs to be done before we can consider this done? goal is to announce/blog about this when it's ready

**Comment by vyzo** [comment]
There are a few things needed before we can open up the testnet:
- Stabilize the grpc frontend
- Run thorough end to end performance testing
- ingest our seed datasets
- have a reasonable client for people to use the testnet, which also provides access to the datastore  (before we start writing to IPFS for good)

Then it is simply a matter of having a few rpc servers in ec2 with the grpc port open to the public.

**Comment by parkan** [comment]
The main thing that worries me is redistributing dynamo write keys

What do you think are the requirements for a "reasonable" client?

**Comment by vyzo** [comment]
I don't think we should distribute dynamo keys to the public -- we can put up an rpc endpoint that accesses the datastore.

For a reasonable client, it should allow end users to insert records and query the medichain at the very least, with a simple interface. Perhaps accept metadata as json?

**Comment by parkan** [comment]
I'm kind of inclined to get it out sooner rather than later (under a VERY EXPERIMENTAL USE AT OWN RISK label) so I think current client w/minor cleanup is probably OK

**Comment by parkan** [comment]
But maybe taking JSON w/o getty reprocessing is a good idea. I'll make an issue

**Comment by denisnazarov** [comment]
@parkan @vyzo other than pulling out the getty code, what needs to be done to have a "reasonable client" for the testnet?

@yusefnapora maybe you can make the issue and include the remaining work on the getty refactor? you brought up questions about author deduplication and where modules should live. 

lets document that in an issue

**Comment by yusefnapora** [comment]
sounds good, I'll update https://github.com/mediachain/mediachain-client/issues/16

**Comment by parkan** [comment]
@denisnazarov https://github.com/mediachain/mediachain/issues/129 + mediachain/mediachain-client#16
